# variables used in the build
variables:
  checkout: master
  packaging_tag: 0.12.6-dev
  iteration: '1'
  pre_release: true
  draft: true

# package builds will always be manually triggered
trigger: none

jobs:
- job: 'docker'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      buster_amd64:
        target: buster-amd64
      stretch_amd64:
        target: stretch-amd64
      bionic_amd64:
        target: bionic-amd64
      xenial_amd64:
        target: xenial-amd64
      centos8_x86_64:
        target: centos8-x86_64
      centos7_x86_64:
        target: centos7-x86_64
      centos6_x86_64:
        target: centos6-x86_64
      mxe_win32:
        target: mxe-cross-win32
      mxe_win64:
        target: mxe-cross-win64
      stretch_raspbian:
        target: raspbian.stretch-armhf
      buster_raspbian:
        target: raspbian.buster-armhf
  timeoutInMinutes: 0
  steps:
  - script: |
      git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build package-docker --iteration $(iteration) $(target) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        targets/*.deb
        targets/*.rpm
        targets/*.7z
