# variables used in the build
variables:
  checkout: 0.12.6
  packaging_tag: 0.12.6-2
  iteration: '2'
  pre_release: false
  draft: false

# package builds will always be manually triggered
trigger: none

jobs:
- job: 'docker'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      # 64-bit x86
      buster_amd64:
        target: buster-amd64
      stretch_amd64:
        target: stretch-amd64
      focal_amd64:
        target: focal-amd64
      bionic_amd64:
        target: bionic-amd64
      xenial_amd64:
        target: xenial-amd64
      centos8_x86_64:
        target: centos8-x86_64
      centos7_x86_64:
        target: centos7-x86_64
      centos6_x86_64:
        target: centos6-x86_64
      amazonlinux2_x86_64:
        target: amazonlinux2-x86_64
      opensuse_leap15_x86_64:
        target: opensuse.leap15-x86_64
      mxe_win32:
        target: mxe-cross-win32
      mxe_win64:
        target: mxe-cross-win64
      # 32-bit x86
      bionic_i386:
        target: bionic-i386
      buster_i386:
        target: buster-i386
      centos6_i686:
        target: centos6-i686
      centos7_i686:
        target: centos7-i686
      stretch_i386:
        target: stretch-i386
      xenial_i386:
        target: xenial-i386
      # 64-bit ARM
      amazonlinux2_aarch64:
        target: amazonlinux2-aarch64
      bionic_arm64:
        target: bionic-arm64
      buster_arm64:
        target: buster-arm64
      centos7_aarch64:
        target: centos7-aarch64
      centos8_aarch64:
        target: centos8-aarch64
      focal_arm64:
        target: focal-arm64
      opensuse_leap15_aarch64:
        target: opensuse.leap15-aarch64
      stretch_arm64:
        target: stretch-arm64
      xenial_arm64:
        target: xenial-arm64
      # 32-bit ARM
      stretch_raspberrypi:
        target: raspberrypi.stretch-armhf
      # PPC
      bionic_ppc64le:
        target: bionic-ppc64le
      buster_ppc64le:
        target: buster-ppc64le
      centos7_ppc64le:
        target: centos7-ppc64le
      focal_ppc64le:
        target: focal-ppc64le
      opensuse_leap15_ppc64le:
        target: opensuse.leap15-ppc64le
  timeoutInMinutes: 0
  condition: eq(1, 2)
  steps:
  - script: |
      echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
      sudo systemctl restart docker
      python build docker-images $(target)
    displayName: 'setup build environment'
  - script: |
      git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build package-docker --clean --iteration $(iteration) $(target) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        targets/*.deb
        targets/*.rpm
        targets/*.7z
- job: 'self_hosted'
  pool:
    name: 'docker'
  strategy:
    matrix:
      buster_raspberrypi:
        target: raspberrypi.buster-armhf
      centos8_ppc64le:
        target: centos8-ppc64le
  timeoutInMinutes: 0
  condition: eq(1, 2)
  steps:
  - script: |
      rm -fr wkhtmltopdf targets && git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build package-docker --clean --iteration $(iteration) $(target) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        targets/*.deb
        targets/*.rpm
        targets/*.7z
- job: 'msvc2015'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      win64:
        target: msvc2015-win64
      win32:
        target: msvc2015-win32
  timeoutInMinutes: 0
  condition: eq(1, 2)
  steps:
  - script: |
      choco install -yr --no-progress vcbuildtools -ia "/Full"
      pip install -q conan
      cmd /c attrib "C:\Program Files (x86)\Windows Kits\10\include\wdf" +H
    displayName: 'install dependencies'
  - script: |
      git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build vagrant $(target) --version - - --iteration $(iteration) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        *.exe
- job: 'macos'
  pool:
    vmImage: 'macOS-10.15'
  strategy:
    matrix:
      cocoa:
        target: macos-cocoa
  timeoutInMinutes: 0
  steps:
  - script: |
      brew install conan
      pip3 install pyyaml
      sudo gem install fpm
      sudo xcode-select --switch /Library/Developer/CommandLineTools
    displayName: 'install dependencies'
  - script: |
      git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
      sed -i -e 's/CFLAGS CXXFLAGS LDFLAGS/CFLAGS CXXFLAGS OBJECTIVE_CFLAGS LDFLAGS/g' qt/configure
      sed -i -e 's/compiler.version=9.0/compiler.version=11.0/g' ../.conan/profiles/macos-cocoa
    displayName: 'clone wkhtmltopdf'
  - script: MACOSX_DEPLOYMENT_TARGET=10.7 python3 build vagrant $(target) --clean --version - - --iteration $(iteration) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        *.pkg
